services:
  pgvector:
    image: pgvector/pgvector:0.8.1-pg16-bookworm
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: githupapp
      POSTGRES_DB: postgres
    restart: always

volumes:
  pgvector_data:
